const USER_DELETED = "USER_DELETED"
const USER_UPDATED = "USER_UPDATED"
const USER_GET = "USER_GET"
const USER_SINGLE = "USER_SINGLE"
const USER_POST = "USER_POST"

export {USER_DELETED,USER_UPDATED,USER_GET,USER_SINGLE,USER_POST}